name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Release
        uses: ADORSYS-GIS/release_generator@v1.0.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_description: "Release of the last full build."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: hagezi
          REPO_NAME: dns-blocklists
          INCREMENTAL_TYPE: minor
