name: Release

env:
  INCREMENTAL_TYPE: major

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Release
        uses: ADORSYS-GIS/release_generator@v1.0.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: hagezi
          REPO_NAME: ${{ secrets.REPO_NAME }}
          INCREMENTAL_TYPE: ${{ env.INCREMENTAL_TYPE }}
